version: "3.2"

services:
  gofiber:
    container_name: gofiber
    image: fiber-apps:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: always
    networks:
      - web-app

networks:
  web-app:
    external: true
    